- name: Roboshop Project - Frontend
  hosts: all
  become: true
  tasks:
    - name: install nginx service
      ansible.builtin.yum:
        name: nginx
        state: installed

    - name: copy roboshop configuration
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: Recursively remove directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: create app directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: download and extract app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: start nginx service
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes


#  source common.sh
#
#  echo -e "\e[36m>>>>>>>>>>>>>>>>>>>>>>>> install nginx service <<<<<<<<<<<<<<<<<<<<<<<<<<\e[0m"
#  yum install nginx -y &>>${log}
#  func_exit_status
#
#  echo -e "\e[36m>>>>>>>>>>>>>>>>>>>>>>>> copy roboshop configuration <<<<<<<<<<<<<<<<<<<<<<<<<<\e[0m"
#  cp nginx.conf /etc/nginx/default.d/roboshop.conf &>>${log}
#  func_exit_status
#
#  echo -e "\e[36m>>>>>>>>>>>>>>>>>>>>>>>> clean old content <<<<<<<<<<<<<<<<<<<<<<<<<<\e[0m"
#  rm -rf /usr/share/nginx/html/* &>>${log}
#  func_exit_status
#
#  echo -e "\e[36m>>>>>>>>>>>>>>>>>>>>>>>> downloading application content <<<<<<<<<<<<<<<<<<<<<<<<<<\e[0m"
#  curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>${log}
#  func_exit_status
#
#  cd /usr/share/nginx/html &>>${log}
#
#  echo -e "\e[36m>>>>>>>>>>>>>>>>>>>>>>>> extracting application content <<<<<<<<<<<<<<<<<<<<<<<<<<\e[0m"
#  unzip /tmp/frontend.zip &>>${log}
#  func_exit_status
#
#  echo -e "\e[36m>>>>>>>>>>>>>>>>>>>>>>>> start nginx service <<<<<<<<<<<<<<<<<<<<<<<<<<\e[0m"
#  systemctl enable nginx &>>${log}
#  systemctl restart nginx &>>${log}
#  func_exit_status


