#cp mongo.repo /etc/yum.repos.d/mongo.repo
#
#yum install mongodb-org -y
#
#sed -i 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf
#systemctl enable mongod
#systemctl restart mongod
#
#

- name: mongo setup
  hosts: all
  become: true
  tasks:
    - name: copy monfo repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb
      ansible.builtin.yum:
        name: mongodb-org
        state: installed

    - name: update listen address
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: restart mongodb
      ansible.builtin.systemd:
        name: mongod
        state: restarted
        enabled: yes


