#echo -e "\e[36m>>>>>>>>>>>>>>>>>>>>>>>> build ${component} service <<<<<<<<<<<<<<<<<<<<<<<<<<\e[0m"
#yum install python36 gcc python3-devel -y &>>${log}
#func_exit_status
#
#func_apppreq
#
#sed -i "s/rabbitmq_app_password/${rabbitmq_app_password}/" /etc/systemd/system/${component}.service
#
#echo -e "\e[36m>>>>>>>>>>>>>>>>>>>>>>>> build ${component} service <<<<<<<<<<<<<<<<<<<<<<<<<<\e[0m"
#pip3.6 install -r requirements.txt &>>${log}
#func_exit_status
#
#func_systemd

- name: install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: app pre-requisites
  ansible.builtin.import_tasks: app-preq.yml

- name: download python dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: systemd setup
  ansible.builtin.import_tasks: systemd-setup.yml