- name: install nginx service
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: copy roboshop configuration
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes